name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: prepare variables
      run: |
        # Change this part with correct version!
        gccver="13.3.rel1"

        # DONT CHANGE PAST THIS LINE
        archiveext=".tar.xz"
        execprefix="arm-none-eabi"
        wgetlink="https://developer.arm.com/-/media/Files/downloads/gnu/${gccver}/binrel/arm-gnu-toolchain-${gccver}-x86_64-${execprefix}${archiveext}"
        
        installprefix="/usr/share"
        installdir="${installprefix}/arm-gnu-toolchain-${gccver}-x86_64-${execprefix}"
        extractto="${installdir}${archiveext}"

        shareprefix="${installdir}/bin/${execprefix}"
        binprefix="/usr/bin/${execprefix}"
    - name: install arm-gcc & deps
      run: |
        sudo apt-get update
        sudo wget -P "$installprefix" "$wgetlink"
        sudo tar -xJf "$extractto" -C "$installprefix"
        
        # This may no longer be required to download
        #sudo apt install libncurses5
    - name: setup symlinks
      run: |
        sudo ln -s "${shareprefix}-g++" "${binprefix}-g++"
        sudo ln -s "${shareprefix}-gcc" "${binprefix}-gcc"
        sudo ln -s "${shareprefix}-objcopy" "${binprefix}-objcopy"
        sudo ln -s "${shareprefix}-objsize" "${binprefix}-objsize"
    - name: run tests
      run: |
          arm-none-eabi-g++ --version
          arm-none-eabi-gcc --version    
    - name: make
      run: make
    # We don't need any tests for now
